services:
  loki:
    image: grafana/loki:3.7.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - .:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml
    restart: unless-stopped
