services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - "GF_SERVER_ROOT_URL=https://grafana.sabihinmolang.eu.org"
      - "GF_SERVER_DOMAIN=grafana.sabihinmolang.eu.org"
      - "GF_SERVER_ENFORCE_DOMAIN=true"
volumes:
  grafana-storage: {}
